name: Generate Snake

on:
  schedule: # har kuni avtomatik ishlaydi
    - cron: "0 0 * * *"
  workflow_dispatch: # qo‘lda ishga tushirish uchun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: shirinov77   # bu yerga username
          outputs: dist/snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

